### ISSUE TITLE
大佬，有没有银河麒麟V10的版本

### ISSUE THREAD

**Issue by Zzy0706** [L-Super/Deepin-QFileDialog#1]
[https://mirror.sjtu.edu.cn/openkylin/pool/main/q/qt5-ukui-platformtheme/qt5-ukui-platformtheme_4.0.0.0.orig.tar.gz](url)

qt5-ukui-platformtheme

**Comment by L-Super** [comment]
没有，麒麟又是另一套了，不通用。当然也可采用同样的逻辑，将qt5-ukui-platformtheme与ukui组件相关的去掉，比如dbus通信等。

**Comment by Zzy0706** [comment]
哈哈哈，真让人头痛，他们维护的版本有点低，我试试看

**Comment by L-Super** [comment]
> 哈哈哈，真让人头痛，他们维护的版本有点低，我试试看

是的，UOS这边也是低版本
